language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=biblio setup.py test
after_success:
  - coveralls